In [200]:
pip install numpy

Requirement already satisfied: numpy in c:\users\cvr\appdata\local\programs\python\python311\lib\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [201]:
import numpy as np

In [202]:
pip install pandas

Requirement already satisfied: pandas in c:\users\cvr\appdata\local\programs\python\python311\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\cvr\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cvr\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\cvr\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\cvr\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [203]:
import pandas as pd
from io import StringIO
data="""

EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
101,John Smith,28,Male,45000,IT,2022-05-12,john.smith@gmail.com,3
102,Alice Johnson,32,Female,52000,HR,2021-08-15,alice@gmail.com,5
103,Bob Williams,,Male,48000,IT,2022/03/20,bob.williams@gmail.com,4
104,Emma Brown,27,Female,,Finance,2023-01-10,emma.brown@gmail.com,2
105,Michael Davis,150,Male,60000,IT,2020-11-05,michael@gmail.com,8
106,Sophia Miller,29,Female,55000,HR,15-06-2021,sophia@gmail,5
107,David Wilson,31,Male,-10000,Finance,2022-07-18,david@gmail.com,6
108,Olivia Moore,26,Female,47000,IT,2023-04-12,olivia@gmail.com,2
109,James Taylor,29,Male,47000,it,2023-04-12,james@gmail.com,2
110,John Smith,28,Male,45000,IT,2022-05-12,john.smith@gmail.com,3
111,,35,Female,58000,HR,2021-02-01,missingname@gmail.com,7
112,Daniel Anderson,abc,Male,50000,Finance,2022-09-09,daniel@gmail.com,4
113,Isabella Thomas,30,Female,9999999,Finance,2022-06-01,isabella@gmail.com,5
114,Ethan Jackson,24,Male,42000,IT,2024-01-01,ethan@gmail.com,1
115,Mia White,29,Female,51000,Marketing,2022-12-15,mia@gmail.com,4
116,Noah Harris,31,Male,53000,Marketing,2022-12-15,noah@gmail.com,4
117,Ava Martin,29,Female,51000,marketing,2022-12-15,ava@gmail.com,4
118,Liam Thompson,30,Male,52000,HR,,liam@gmail.com,5
119,Charlotte Garcia,28,Female,49000,Finance,2022-10-10,charlotte@gmail.com,3
120,William Martinez,29,Male,50000,IT,2022-08-08,william@gmail.com,3"""
df=pd.read_csv(StringIO(data))
df_co=df.copy()

In [204]:
df_co['Age']=pd.to_numeric(df_co['Age'],errors='coerce')

In [205]:
df_co=df_co.dropna(subset=['Name'])

In [206]:
df_co

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
0,101,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
1,102,Alice Johnson,32.0,Female,52000.0,HR,2021-08-15,alice@gmail.com,5
2,103,Bob Williams,NaN,Male,48000.0,IT,2022/03/20,bob.williams@gmail.com,4
3,104,Emma Brown,27.0,Female,NaN,Finance,2023-01-10,emma.brown@gmail.com,2
4,105,Michael Davis,150.0,Male,60000.0,IT,2020-11-05,michael@gmail.com,8
5,106,Sophia Miller,29.0,Female,55000.0,HR,15-06-2021,sophia@gmail,5
6,107,David Wilson,31.0,Male,-10000.0,Finance,2022-07-18,david@gmail.com,6
7,108,Olivia Moore,26.0,Female,47000.0,IT,2023-04-12,olivia@gmail.com,2
8,109,James Taylor,29.0,Male,47000.0,it,2023-04-12,james@gmail.com,2
9,110,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
11,112,Daniel Anderson,NaN,Male,50000.0,Finance,2022-09-09,daniel@gmail.com,4
12,113,Isabella Thomas,30.0,Female,9999999.0,Finance,2022-06-01,isabella@gmail.com,5
13,114,Ethan Jackson,24.0,Male,42000.0,IT,2024-01-01,ethan@gmail.com,1
14,115,Mia White,29.0,Female,51000.0,Marketing,2022-12-15,mia@gmail.com,4
15,116,Noah Harris,31.0,Male,53000.0,Marketing,2022-12-15,noah@gmail.com,4
16,117,Ava Martin,29.0,Female,51000.0,marketing,2022-12-15,ava@gmail.com,4
17,118,Liam Thompson,30.0,Male,52000.0,HR,NaN,liam@gmail.com,5
18,119,Charlotte Garcia,28.0,Female,49000.0,Finance,2022-10-10,charlotte@gmail.com,3
19,120,William Martinez,29.0,Male,50000.0,IT,2022-08-08,william@gmail.com,3

In [207]:
neg_row=df_co[df_co['Salary']<0]
neg_row
df_co.drop(neg_row.index,inplace=True)

In [208]:
df_co

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
0,101,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
1,102,Alice Johnson,32.0,Female,52000.0,HR,2021-08-15,alice@gmail.com,5
2,103,Bob Williams,NaN,Male,48000.0,IT,2022/03/20,bob.williams@gmail.com,4
3,104,Emma Brown,27.0,Female,NaN,Finance,2023-01-10,emma.brown@gmail.com,2
4,105,Michael Davis,150.0,Male,60000.0,IT,2020-11-05,michael@gmail.com,8
5,106,Sophia Miller,29.0,Female,55000.0,HR,15-06-2021,sophia@gmail,5
7,108,Olivia Moore,26.0,Female,47000.0,IT,2023-04-12,olivia@gmail.com,2
8,109,James Taylor,29.0,Male,47000.0,it,2023-04-12,james@gmail.com,2
9,110,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
11,112,Daniel Anderson,NaN,Male,50000.0,Finance,2022-09-09,daniel@gmail.com,4
12,113,Isabella Thomas,30.0,Female,9999999.0,Finance,2022-06-01,isabella@gmail.com,5
13,114,Ethan Jackson,24.0,Male,42000.0,IT,2024-01-01,ethan@gmail.com,1
14,115,Mia White,29.0,Female,51000.0,Marketing,2022-12-15,mia@gmail.com,4
15,116,Noah Harris,31.0,Male,53000.0,Marketing,2022-12-15,noah@gmail.com,4
16,117,Ava Martin,29.0,Female,51000.0,marketing,2022-12-15,ava@gmail.com,4
17,118,Liam Thompson,30.0,Male,52000.0,HR,NaN,liam@gmail.com,5
18,119,Charlotte Garcia,28.0,Female,49000.0,Finance,2022-10-10,charlotte@gmail.com,3
19,120,William Martinez,29.0,Male,50000.0,IT,2022-08-08,william@gmail.com,3

In [209]:
df_co['Salary'].median()

np.float64(50000.0)

In [210]:
df_co.fillna(df_co['Salary'].median())

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
0,101,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
1,102,Alice Johnson,32.0,Female,52000.0,HR,2021-08-15,alice@gmail.com,5
2,103,Bob Williams,50000.0,Male,48000.0,IT,2022/03/20,bob.williams@gmail.com,4
3,104,Emma Brown,27.0,Female,50000.0,Finance,2023-01-10,emma.brown@gmail.com,2
4,105,Michael Davis,150.0,Male,60000.0,IT,2020-11-05,michael@gmail.com,8
5,106,Sophia Miller,29.0,Female,55000.0,HR,15-06-2021,sophia@gmail,5
7,108,Olivia Moore,26.0,Female,47000.0,IT,2023-04-12,olivia@gmail.com,2
8,109,James Taylor,29.0,Male,47000.0,it,2023-04-12,james@gmail.com,2
9,110,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
11,112,Daniel Anderson,50000.0,Male,50000.0,Finance,2022-09-09,daniel@gmail.com,4
12,113,Isabella Thomas,30.0,Female,9999999.0,Finance,2022-06-01,isabella@gmail.com,5
13,114,Ethan Jackson,24.0,Male,42000.0,IT,2024-01-01,ethan@gmail.com,1
14,115,Mia White,29.0,Female,51000.0,Marketing,2022-12-15,mia@gmail.com,4
15,116,Noah Harris,31.0,Male,53000.0,Marketing,2022-12-15,noah@gmail.com,4
16,117,Ava Martin,29.0,Female,51000.0,marketing,2022-12-15,ava@gmail.com,4
17,118,Liam Thompson,30.0,Male,52000.0,HR,50000.0,liam@gmail.com,5
18,119,Charlotte Garcia,28.0,Female,49000.0,Finance,2022-10-10,charlotte@gmail.com,3
19,120,William Martinez,29.0,Male,50000.0,IT,2022-08-08,william@gmail.com,3

In [211]:
df_co

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
0,101,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
1,102,Alice Johnson,32.0,Female,52000.0,HR,2021-08-15,alice@gmail.com,5
2,103,Bob Williams,NaN,Male,48000.0,IT,2022/03/20,bob.williams@gmail.com,4
3,104,Emma Brown,27.0,Female,NaN,Finance,2023-01-10,emma.brown@gmail.com,2
4,105,Michael Davis,150.0,Male,60000.0,IT,2020-11-05,michael@gmail.com,8
5,106,Sophia Miller,29.0,Female,55000.0,HR,15-06-2021,sophia@gmail,5
7,108,Olivia Moore,26.0,Female,47000.0,IT,2023-04-12,olivia@gmail.com,2
8,109,James Taylor,29.0,Male,47000.0,it,2023-04-12,james@gmail.com,2
9,110,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
11,112,Daniel Anderson,NaN,Male,50000.0,Finance,2022-09-09,daniel@gmail.com,4
12,113,Isabella Thomas,30.0,Female,9999999.0,Finance,2022-06-01,isabella@gmail.com,5
13,114,Ethan Jackson,24.0,Male,42000.0,IT,2024-01-01,ethan@gmail.com,1
14,115,Mia White,29.0,Female,51000.0,Marketing,2022-12-15,mia@gmail.com,4
15,116,Noah Harris,31.0,Male,53000.0,Marketing,2022-12-15,noah@gmail.com,4
16,117,Ava Martin,29.0,Female,51000.0,marketing,2022-12-15,ava@gmail.com,4
17,118,Liam Thompson,30.0,Male,52000.0,HR,NaN,liam@gmail.com,5
18,119,Charlotte Garcia,28.0,Female,49000.0,Finance,2022-10-10,charlotte@gmail.com,3
19,120,William Martinez,29.0,Male,50000.0,IT,2022-08-08,william@gmail.com,3

In [212]:
df_co=df_co.drop_duplicates(subset=['Name'])

In [213]:
df_co

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
0,101,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
1,102,Alice Johnson,32.0,Female,52000.0,HR,2021-08-15,alice@gmail.com,5
2,103,Bob Williams,NaN,Male,48000.0,IT,2022/03/20,bob.williams@gmail.com,4
3,104,Emma Brown,27.0,Female,NaN,Finance,2023-01-10,emma.brown@gmail.com,2
4,105,Michael Davis,150.0,Male,60000.0,IT,2020-11-05,michael@gmail.com,8
5,106,Sophia Miller,29.0,Female,55000.0,HR,15-06-2021,sophia@gmail,5
7,108,Olivia Moore,26.0,Female,47000.0,IT,2023-04-12,olivia@gmail.com,2
8,109,James Taylor,29.0,Male,47000.0,it,2023-04-12,james@gmail.com,2
11,112,Daniel Anderson,NaN,Male,50000.0,Finance,2022-09-09,daniel@gmail.com,4
12,113,Isabella Thomas,30.0,Female,9999999.0,Finance,2022-06-01,isabella@gmail.com,5
13,114,Ethan Jackson,24.0,Male,42000.0,IT,2024-01-01,ethan@gmail.com,1
14,115,Mia White,29.0,Female,51000.0,Marketing,2022-12-15,mia@gmail.com,4
15,116,Noah Harris,31.0,Male,53000.0,Marketing,2022-12-15,noah@gmail.com,4
16,117,Ava Martin,29.0,Female,51000.0,marketing,2022-12-15,ava@gmail.com,4
17,118,Liam Thompson,30.0,Male,52000.0,HR,NaN,liam@gmail.com,5
18,119,Charlotte Garcia,28.0,Female,49000.0,Finance,2022-10-10,charlotte@gmail.com,3
19,120,William Martinez,29.0,Male,50000.0,IT,2022-08-08,william@gmail.com,3

In [214]:
df_co.drop_duplicates(subset=['Name'])

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
0,101,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
1,102,Alice Johnson,32.0,Female,52000.0,HR,2021-08-15,alice@gmail.com,5
2,103,Bob Williams,NaN,Male,48000.0,IT,2022/03/20,bob.williams@gmail.com,4
3,104,Emma Brown,27.0,Female,NaN,Finance,2023-01-10,emma.brown@gmail.com,2
4,105,Michael Davis,150.0,Male,60000.0,IT,2020-11-05,michael@gmail.com,8
5,106,Sophia Miller,29.0,Female,55000.0,HR,15-06-2021,sophia@gmail,5
7,108,Olivia Moore,26.0,Female,47000.0,IT,2023-04-12,olivia@gmail.com,2
8,109,James Taylor,29.0,Male,47000.0,it,2023-04-12,james@gmail.com,2
11,112,Daniel Anderson,NaN,Male,50000.0,Finance,2022-09-09,daniel@gmail.com,4
12,113,Isabella Thomas,30.0,Female,9999999.0,Finance,2022-06-01,isabella@gmail.com,5
13,114,Ethan Jackson,24.0,Male,42000.0,IT,2024-01-01,ethan@gmail.com,1
14,115,Mia White,29.0,Female,51000.0,Marketing,2022-12-15,mia@gmail.com,4
15,116,Noah Harris,31.0,Male,53000.0,Marketing,2022-12-15,noah@gmail.com,4
16,117,Ava Martin,29.0,Female,51000.0,marketing,2022-12-15,ava@gmail.com,4
17,118,Liam Thompson,30.0,Male,52000.0,HR,NaN,liam@gmail.com,5
18,119,Charlotte Garcia,28.0,Female,49000.0,Finance,2022-10-10,charlotte@gmail.com,3
19,120,William Martinez,29.0,Male,50000.0,IT,2022-08-08,william@gmail.com,3

In [215]:
df_co[df_co['Age']>100]

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
4,105,Michael Davis,150.0,Male,60000.0,IT,2020-11-05,michael@gmail.com,8

In [216]:
#to replace we use loc
df_co.loc[df_co['Age']>100,'Age']=pd.NA

In [217]:
df_co

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
0,101,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
1,102,Alice Johnson,32.0,Female,52000.0,HR,2021-08-15,alice@gmail.com,5
2,103,Bob Williams,NaN,Male,48000.0,IT,2022/03/20,bob.williams@gmail.com,4
3,104,Emma Brown,27.0,Female,NaN,Finance,2023-01-10,emma.brown@gmail.com,2
4,105,Michael Davis,NaN,Male,60000.0,IT,2020-11-05,michael@gmail.com,8
5,106,Sophia Miller,29.0,Female,55000.0,HR,15-06-2021,sophia@gmail,5
7,108,Olivia Moore,26.0,Female,47000.0,IT,2023-04-12,olivia@gmail.com,2
8,109,James Taylor,29.0,Male,47000.0,it,2023-04-12,james@gmail.com,2
11,112,Daniel Anderson,NaN,Male,50000.0,Finance,2022-09-09,daniel@gmail.com,4
12,113,Isabella Thomas,30.0,Female,9999999.0,Finance,2022-06-01,isabella@gmail.com,5
13,114,Ethan Jackson,24.0,Male,42000.0,IT,2024-01-01,ethan@gmail.com,1
14,115,Mia White,29.0,Female,51000.0,Marketing,2022-12-15,mia@gmail.com,4
15,116,Noah Harris,31.0,Male,53000.0,Marketing,2022-12-15,noah@gmail.com,4
16,117,Ava Martin,29.0,Female,51000.0,marketing,2022-12-15,ava@gmail.com,4
17,118,Liam Thompson,30.0,Male,52000.0,HR,NaN,liam@gmail.com,5
18,119,Charlotte Garcia,28.0,Female,49000.0,Finance,2022-10-10,charlotte@gmail.com,3
19,120,William Martinez,29.0,Male,50000.0,IT,2022-08-08,william@gmail.com,3

In [218]:
df_co['Salary'].median()

np.float64(50500.0)

In [219]:
df_co['Salary']=df_co['Salary'].fillna(df_co['Salary'].median(),inplace=True)

C:\Users\CVR\AppData\Local\Temp\ipykernel_13492\207116777.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_co['Salary']=df_co['Salary'].fillna(df_co['Salary'].median(),inplace=True)

In [220]:
df_co

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
0,101,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
1,102,Alice Johnson,32.0,Female,52000.0,HR,2021-08-15,alice@gmail.com,5
2,103,Bob Williams,NaN,Male,48000.0,IT,2022/03/20,bob.williams@gmail.com,4
3,104,Emma Brown,27.0,Female,50500.0,Finance,2023-01-10,emma.brown@gmail.com,2
4,105,Michael Davis,NaN,Male,60000.0,IT,2020-11-05,michael@gmail.com,8
5,106,Sophia Miller,29.0,Female,55000.0,HR,15-06-2021,sophia@gmail,5
7,108,Olivia Moore,26.0,Female,47000.0,IT,2023-04-12,olivia@gmail.com,2
8,109,James Taylor,29.0,Male,47000.0,it,2023-04-12,james@gmail.com,2
11,112,Daniel Anderson,NaN,Male,50000.0,Finance,2022-09-09,daniel@gmail.com,4
12,113,Isabella Thomas,30.0,Female,9999999.0,Finance,2022-06-01,isabella@gmail.com,5
13,114,Ethan Jackson,24.0,Male,42000.0,IT,2024-01-01,ethan@gmail.com,1
14,115,Mia White,29.0,Female,51000.0,Marketing,2022-12-15,mia@gmail.com,4
15,116,Noah Harris,31.0,Male,53000.0,Marketing,2022-12-15,noah@gmail.com,4
16,117,Ava Martin,29.0,Female,51000.0,marketing,2022-12-15,ava@gmail.com,4
17,118,Liam Thompson,30.0,Male,52000.0,HR,NaN,liam@gmail.com,5
18,119,Charlotte Garcia,28.0,Female,49000.0,Finance,2022-10-10,charlotte@gmail.com,3
19,120,William Martinez,29.0,Male,50000.0,IT,2022-08-08,william@gmail.com,3

In [221]:
#we hava a outlier in the salary col which 9999999
#inorder to deal with that we have to perfor IQR
#to find the abnormal salalries sort it 
df_co['Salary'].sort_values()

13      42000.0
0       45000.0
7       47000.0
8       47000.0
2       48000.0
18      49000.0
11      50000.0
19      50000.0
3       50500.0
16      51000.0
14      51000.0
1       52000.0
17      52000.0
15      53000.0
5       55000.0
4       60000.0
12    9999999.0
Name: Salary, dtype: float64

In [222]:
#IQR
q1=df_co['Salary'].quantile(0.25)
q3=df_co['Salary'].quantile(0.75)
iqr=q3-q1
lower=q1-1.5*iqr
upper=q1+1.5*iqr
print(f"{q1},{iqr},{q3}")
ou=df_co[(df_co['Salary']<lower) | (df_co['Salary']>upper)]
ou

48000.0,4000.0,52000.0

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
4,105,Michael Davis,NaN,Male,60000.0,IT,2020-11-05,michael@gmail.com,8
5,106,Sophia Miller,29.0,Female,55000.0,HR,15-06-2021,sophia@gmail,5
12,113,Isabella Thomas,30.0,Female,9999999.0,Finance,2022-06-01,isabella@gmail.com,5

In [224]:
df_co=df_co[(df_co['Salary']>=lower) & (df_co['Salary']<=upper)]
df_co

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Email,Experience
0,101,John Smith,28.0,Male,45000.0,IT,2022-05-12,john.smith@gmail.com,3
1,102,Alice Johnson,32.0,Female,52000.0,HR,2021-08-15,alice@gmail.com,5
2,103,Bob Williams,NaN,Male,48000.0,IT,2022/03/20,bob.williams@gmail.com,4
3,104,Emma Brown,27.0,Female,50500.0,Finance,2023-01-10,emma.brown@gmail.com,2
7,108,Olivia Moore,26.0,Female,47000.0,IT,2023-04-12,olivia@gmail.com,2
8,109,James Taylor,29.0,Male,47000.0,it,2023-04-12,james@gmail.com,2
11,112,Daniel Anderson,NaN,Male,50000.0,Finance,2022-09-09,daniel@gmail.com,4
13,114,Ethan Jackson,24.0,Male,42000.0,IT,2024-01-01,ethan@gmail.com,1
14,115,Mia White,29.0,Female,51000.0,Marketing,2022-12-15,mia@gmail.com,4
15,116,Noah Harris,31.0,Male,53000.0,Marketing,2022-12-15,noah@gmail.com,4
16,117,Ava Martin,29.0,Female,51000.0,marketing,2022-12-15,ava@gmail.com,4
17,118,Liam Thompson,30.0,Male,52000.0,HR,NaN,liam@gmail.com,5
18,119,Charlotte Garcia,28.0,Female,49000.0,Finance,2022-10-10,charlotte@gmail.com,3
19,120,William Martinez,29.0,Male,50000.0,IT,2022-08-08,william@gmail.com,3

In [225]:
df['Department'].unique()

<StringArray>
['IT', 'HR', 'Finance', 'it', 'Marketing', 'marketing']
Length: 6, dtype: str

In [ ]:
df_co['Department'] = (
    df_co['Department']
    .str.upper()
)